ACS-5039 - Added a arm65 Libreoffice rpm, changes to allow build multiarch image for Libreoffice and aio

diff --git a/engines/aio/Dockerfile b/engines/aio/Dockerfile
--- a/engines/aio/Dockerfile
+++ b/engines/aio/Dockerfile
@@ -12,12 +12,15 @@ ARG EXIFTOOL_FOLDER=Image-ExifTool-${EXIFTOOL_VERSION}
 ARG EXIFTOOL_URL=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/exiftool/image-exiftool/${EXIFTOOL_VERSION}/image-exiftool-${EXIFTOOL_VERSION}.tgz
 
 ARG IMAGEMAGICK_VERSION=7.1.0-16
-ENV IMAGEMAGICK_RPM_URL=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-${IMAGEMAGICK_VERSION}.x86_64.rpm
-ENV IMAGEMAGICK_LIB_RPM_URL=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-libs-${IMAGEMAGICK_VERSION}.x86_64.rpm
+ENV IMAGEMAGICK_RPM_URL_AMD64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-${IMAGEMAGICK_VERSION}.x86_64.rpm
+ENV IMAGEMAGICK_LIB_RPM_URL_AMD64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-libs-${IMAGEMAGICK_VERSION}.x86_64.rpm
+ENV IMAGEMAGICK_RPM_URL_ARM64=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/imagemagick/imagemagick-distribution/7.1.0-16-ci-3/imagemagick-distribution-7.1.0-16-ci-3-arm64.rpm
+ENV IMAGEMAGICK_LIB_RPM_URL_ARM64=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/imagemagick/imagemagick-distribution/7.1.0-16-ci-3/imagemagick-distribution-7.1.0-16-ci-3-arm64-libs.rpm
 ENV IMAGEMAGICK_DEP_RPM_URL=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
 
 ARG LIBREOFFICE_VERSION=7.2.5
 ENV LIBREOFFICE_RPM_URL=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/libreoffice/libreoffice-dist/${LIBREOFFICE_VERSION}/libreoffice-dist-${LIBREOFFICE_VERSION}-linux.gz
+ENV LIBREOFFICE_ARM64_RPM_URL=https://dl.rockylinux.org/pub/rocky/8.8/devel/aarch64/os/Packages/l/libreoffice-core-6.4.7.2-13.el8.aarch64.rpm
 
 ENV ALFRESCO_PDF_RENDERER_LIB_RPM_URL=https://nexus.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-pdf-renderer/1.1/alfresco-pdf-renderer-1.1-linux.tgz
 
@@ -34,15 +37,24 @@ COPY target/${env.project_artifactId}-${env.project_version}.jar /usr/bin
 #removing perl-ExtUtils-MakeMaker cascades to remove exiftools
 RUN ln /usr/bin/${env.project_artifactId}-${env.project_version}.jar /usr/bin/${env.project_artifactId}.jar && \
     yum install -y $IMAGEMAGICK_DEP_RPM_URL && \
-    yum install -y $IMAGEMAGICK_LIB_RPM_URL $IMAGEMAGICK_RPM_URL && \
-    rpm -e --nodeps libgs && \
+    if [ "$(uname -m)" = "x86_64" ]; then \
+                yum install -y $IMAGEMAGICK_LIB_RPM_URL_AMD64 $IMAGEMAGICK_RPM_URL_AMD64; \
+            else \
+                yum install -y $IMAGEMAGICK_LIB_RPM_URL_ARM64 $IMAGEMAGICK_RPM_URL_ARM64; \
+            fi && \
+    rpm -qa | grep libgs && rpm -e --nodeps libgs || echo "libgs package not found" && \
     yum install -y cairo cups-libs libSM libGLU && \
-    test -f libreoffice-dist-${LIBREOFFICE_VERSION}-linux.gz && \
-    ln -s libreoffice-dist-${LIBREOFFICE_VERSION}-linux.gz libreoffice-dist-linux.gz || \
-    curl -s -S $LIBREOFFICE_RPM_URL      -o libreoffice-dist-linux.gz && \
-    tar xzf libreoffice-dist-linux.gz && \
-    yum localinstall -y LibreOffice*/RPMS/*.rpm && \
-    rm -rf libreoffice-dist-*linux.gz LibreOffice_*_Linux_x86-64_rpm && \
+    if [ "$(uname -m)" = "x86_64" ]; then \
+      test -f libreoffice-dist-${LIBREOFFICE_VERSION}-linux.gz && \
+      ln -s libreoffice-dist-${LIBREOFFICE_VERSION}-linux.gz libreoffice-dist-linux.gz || \
+      curl -s -S $LIBREOFFICE_RPM_URL      -o libreoffice-dist-linux.gz && \
+      tar xzf libreoffice-dist-linux.gz && \
+      yum localinstall -y LibreOffice*/RPMS/*.rpm && \
+      rm -rf libreoffice-dist-*linux.gz LibreOffice_*_Linux_x86-64_rpm; \
+    else \
+      yum install -y $LIBREOFFICE_ARM64_RPM_URL && \
+      update-alternatives --set java java-17-openjdk.aarch64; \
+    fi && \
     curl -s -S $ALFRESCO_PDF_RENDERER_LIB_RPM_URL -o alfresco-pdf-renderer-linux.tgz && \
     tar xf alfresco-pdf-renderer-linux.tgz -C /usr/bin && \
 	rm -f alfresco-pdf-renderer-linux.tgz && \
