ACS-5039 - Changes in imagemagick Dockerfile and pom to allow produce a multiarch images

diff --git a/engines/imagemagick/Dockerfile b/engines/imagemagick/Dockerfile
--- a/engines/imagemagick/Dockerfile
+++ b/engines/imagemagick/Dockerfile
@@ -9,10 +9,11 @@ ARG IMAGEMAGICK_VERSION=7.1.0-16
 
 ENV IMAGEMAGICK_RPM_URL_AMD64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-${IMAGEMAGICK_VERSION}.x86_64.rpm
 ENV IMAGEMAGICK_LIB_RPM_URL_AMD64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-libs-${IMAGEMAGICK_VERSION}.x86_64.rpm
-ENV IMAGEMAGICK_DEP_RPM_URL=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
-ENV IMAGEMAGICK_RPM_URL_ARM64=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/imagemagick/imagemagick-distribution/7.1.0-16-ci-3/imagemagick-distribution-7.1.0-16-ci-3-arm64.rpm
-ENV IMAGEMAGICK_LIB_RPM_URL_ARM64=https://nexus.alfresco.com/nexus/service/local/repositories/thirdparty/content/org/imagemagick/imagemagick-distribution/7.1.0-16-ci-3/imagemagick-distribution-7.1.0-16-ci-3-arm64-libs.rpm
 
+ENV IMAGEMAGICK_RPM_URL_ARM64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-${IMAGEMAGICK_VERSION}.arm64.rpm
+ENV IMAGEMAGICK_LIB_RPM_URL_ARM64=https://github.com/Alfresco/imagemagick-build/releases/download/v${IMAGEMAGICK_VERSION}/ImageMagick-libs-${IMAGEMAGICK_VERSION}.arm64.rpm
+
+ENV IMAGEMAGICK_DEP_RPM_URL=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
 
 ENV JAVA_OPTS=""
 
@@ -24,8 +25,6 @@ ARG USERID=33002
 
 COPY target/${env.project_artifactId}-${env.project_version}.jar /usr/bin
 
-RUN echo "Architecture: $(uname -m)"
-
 RUN ln /usr/bin/${env.project_artifactId}-${env.project_version}.jar /usr/bin/${env.project_artifactId}.jar && \
     yum install -y $IMAGEMAGICK_DEP_RPM_URL && \
     if [ "$(uname -m)" = "x86_64" ]; then \
@@ -33,9 +32,8 @@ RUN ln /usr/bin/${env.project_artifactId}-${env.project_version}.jar /usr/bin/${
         else \
             yum install -y $IMAGEMAGICK_LIB_RPM_URL_ARM64 $IMAGEMAGICK_RPM_URL_ARM64; \
         fi && \
-    yum clean all
-#    yum clean all && \
-#    rpm -e --nodeps libgs
+    yum clean all && \
+    rpm -qa | grep libgs && rpm -e --nodeps libgs || echo "libgs package not found"
 
 ADD target/generated-resources/licenses              /licenses
 ADD target/generated-resources/licenses.xml          /licenses/
